# Site Build Settings

# Jekyll-paginate-v2 configuration
#  pagination:
#   enabled: true
#   per_page: 5
#   permalink: '/page/:num/'
#   title: ':title - page :num of :max'
#   limit: 0
#   sort_field: 'date'
#   sort_reverse: true

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:categories/:name
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           'Tei Juan'
description:	       'Toons in 2D and CGI'
author:              'João Marcelo Teixeira'
logo:                '/assets/img/logo.svg'

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
feed:
  posts_limit: 20
  collections:
    models:
      path: "/models/feed.xml"
    artworks:
      path: "/artworks/feed.xml"

collections_dir: collections
collections:
  posts:
    output: true
    permalink: /:categories/:name
  models:
    output: true
    permalink: /models/:categories/:slug
  artworks:
    output: true
    permalink: /:name

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "_artworks"
      type: "artworks"
    values:
      layout: "artwork"
      image: /assets/img/2d-art/:slug.jpg
  - scope:
      path: ""
      type: "models"
    values:
      layout: "model"
      icon: /assets/ic/models/:slug.jpg
      image: /favicon.svg
