# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'G-S1ZEVG6K59'

menu:
- {name: 'About',   url: 'about'}
- {name: 'Portfolio <sup>Beta</sup>',   url: 'portfolio'}
- {name: 'Writing', url: 'writing'}
- {name: 'Queue', url: 'queue'}
- {name: 'TOS', url: 'tos'}
- {name: 'Fanarts', url: 'fanarts'}
- {name: 'Contact', url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter',    link: 'https://twitter.com/teijuanart'}
- {icon: 'instagram',  link: 'https://www.instagram.com/tei.juan/'}
- {icon: 'tumblr',  link: 'https://www.tumblr.com/teijuan/'}
- {icon: 'itaku', link: 'https://itaku.ee/profile/teijuan'}
- {icon: 'deviantart',  link: 'https://www.deviantart.com/tei-juan/'}
- {icon: 'envelope',   link: 'mailto:tei-juan@hotmail.com'}
- {icon: 'rss-square', link: '/feed.xml'}
#- {icon: 'linkedin',   link: 'https://www.linkedin.com/in/lenpaul/'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Share:'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'

some_quote: '"Joy is found on the journey, not in destination." - Greg Anderson'
