google-ID: 'G-S1ZEVG6K59'

menu:
  #- {name: 'Gallery', url: '/gallery'}
- {name: 'TOS', url: '/tos'}
- {name: 'Queue', url: '/queue'}
- {name: 'Models',   url: '/models'}
- {name: 'Writing', url: '/writing'}
- {name: 'Contact', url: '/contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'image',  link: 'https://www.artstation.com/teijuan/'}
- {icon: 'instagram',  link: 'https://www.instagram.com/tei.juan/'}
- {icon: 'envelope',   link: 'mailto:tei-juan@hotmail.com'}
- {icon: 'rss-square', link: '/feed.xml'}
#- {icon: 'linkedin',   link: 'https://www.linkedin.com/in/lenpaul/'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Share:'

related_posts: 'You may also enjoy:'

post_date_prefix: '<i class="fa fa-calendar" aria-hidden="true"></i>'

# Predefined messsages
wipmsg: "Work In Progress.."
bdgnew: '<sup><span class="bdgnew">**NEW!**</span></sup>'
bdgwip: '<span class="bdgwip">Work in Progress</span>'
